# Generated by Django 5.2.4 on 2025-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
